<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CustomersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('customers')->delete();
        
        \DB::table('customers')->insert(array (
            0 => 
            array (
                'id' => 1,
                'photo' => NULL,
                'last_name' => 'Mraz',
                'first_name' => 'Maynard',
                'date_of_birth' => '2022-03-15',
                'contact_number' => '1-458-212-8015',
                'email' => 'lhoppe@example.net',
                'block_street' => '53578 Moore Port Suite 216',
                'barangay' => 'port',
                'city_or_municipality' => 'New Mercedes',
                'social_media' => 'ettie12',
                'signature' => 'https://via.placeholder.com/640x480.png/001111?text=amet',
                'created_at' => '2024-06-28 09:20:04',
                'updated_at' => '2024-06-28 09:20:04',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'photo' => NULL,
                'last_name' => 'Johnston',
                'first_name' => 'Kaelyn',
                'date_of_birth' => '2021-02-04',
                'contact_number' => '+1-458-789-0362',
                'email' => 'muriel.brekke@example.com',
                'block_street' => '36333 Maybell Shoal Suite 068',
                'barangay' => 'mouth',
                'city_or_municipality' => 'Franciscafort',
                'social_media' => 'ara51',
                'signature' => 'https://via.placeholder.com/640x480.png/00ff22?text=beatae',
                'created_at' => '2024-06-28 09:20:04',
                'updated_at' => '2024-06-28 09:20:04',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'photo' => NULL,
                'last_name' => 'Bartoletti',
                'first_name' => 'Haskell',
                'date_of_birth' => '2018-01-05',
                'contact_number' => '731-796-8137',
                'email' => 'howell.towne@example.com',
                'block_street' => '6646 Corkery Crescent',
                'barangay' => 'shire',
                'city_or_municipality' => 'East Rylanport',
                'social_media' => 'dicki.davion',
                'signature' => 'https://via.placeholder.com/640x480.png/007711?text=est',
                'created_at' => '2024-06-28 09:20:04',
                'updated_at' => '2024-06-28 09:20:04',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'photo' => NULL,
                'last_name' => 'Trantow',
                'first_name' => 'Earnest',
                'date_of_birth' => '2014-08-01',
            'contact_number' => '(862) 434-9053',
                'email' => 'wreichert@example.com',
                'block_street' => '35077 Robel Inlet',
                'barangay' => 'stad',
                'city_or_municipality' => 'Lake Ara',
                'social_media' => 'rdicki',
                'signature' => 'https://via.placeholder.com/640x480.png/004488?text=sit',
                'created_at' => '2024-06-28 09:20:04',
                'updated_at' => '2024-06-28 09:20:04',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'photo' => NULL,
                'last_name' => 'Considine',
                'first_name' => 'Lourdes',
                'date_of_birth' => '2016-01-06',
                'contact_number' => '+14192891991',
                'email' => 'asha10@example.com',
                'block_street' => '13954 Lucio Well',
                'barangay' => 'bury',
                'city_or_municipality' => 'Creminmouth',
                'social_media' => 'cordell.bednar',
                'signature' => 'https://via.placeholder.com/640x480.png/002277?text=et',
                'created_at' => '2024-06-28 09:20:04',
                'updated_at' => '2024-06-28 09:20:04',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'photo' => NULL,
                'last_name' => 'Nolan',
                'first_name' => 'Jessy',
                'date_of_birth' => '1990-08-23',
                'contact_number' => '878.739.3362',
                'email' => 'saul.west@example.org',
                'block_street' => '3961 Isabelle Curve',
                'barangay' => 'chester',
                'city_or_municipality' => 'North Nella',
                'social_media' => 'uturner',
                'signature' => 'https://via.placeholder.com/640x480.png/00cc88?text=et',
                'created_at' => '2024-06-28 09:20:04',
                'updated_at' => '2024-06-28 09:20:04',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'photo' => NULL,
                'last_name' => 'Lakin',
                'first_name' => 'Raven',
                'date_of_birth' => '1973-12-29',
                'contact_number' => '+1.283.356.0488',
                'email' => 'jbernier@example.com',
                'block_street' => '41009 Hirthe Crossroad',
                'barangay' => 'shire',
                'city_or_municipality' => 'Kaileyville',
                'social_media' => 'tupton',
                'signature' => 'https://via.placeholder.com/640x480.png/0044bb?text=quidem',
                'created_at' => '2024-06-28 09:20:04',
                'updated_at' => '2024-06-28 09:20:04',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'photo' => NULL,
                'last_name' => 'Stroman',
                'first_name' => 'Kareem',
                'date_of_birth' => '1971-08-08',
                'contact_number' => '302.483.5006',
                'email' => 'ugoyette@example.com',
                'block_street' => '66916 Weimann Flat',
                'barangay' => 'mouth',
                'city_or_municipality' => 'New Manleyburgh',
                'social_media' => 'batz.khalil',
                'signature' => 'https://via.placeholder.com/640x480.png/00ee33?text=sit',
                'created_at' => '2024-06-28 09:20:04',
                'updated_at' => '2024-06-28 09:20:04',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'photo' => NULL,
                'last_name' => 'Bernhard',
                'first_name' => 'Halie',
                'date_of_birth' => '2014-09-29',
                'contact_number' => '323-807-2360',
                'email' => 'beau43@example.org',
                'block_street' => '26794 Howell Coves Suite 435',
                'barangay' => 'borough',
                'city_or_municipality' => 'West Nadiaton',
                'social_media' => 'dsipes',
                'signature' => 'https://via.placeholder.com/640x480.png/00ee66?text=voluptatem',
                'created_at' => '2024-06-28 09:20:04',
                'updated_at' => '2024-06-28 09:20:04',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'photo' => NULL,
                'last_name' => 'Moen',
                'first_name' => 'Addison',
                'date_of_birth' => '1998-07-05',
                'contact_number' => '1-747-754-9124',
                'email' => 'jokeefe@example.com',
                'block_street' => '72619 Rolfson Mountains Suite 837',
                'barangay' => 'side',
                'city_or_municipality' => 'Lake Ronaldostad',
                'social_media' => 'javier74',
                'signature' => 'https://via.placeholder.com/640x480.png/0022ee?text=itaque',
                'created_at' => '2024-06-28 09:20:04',
                'updated_at' => '2024-06-28 09:20:04',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'photo' => NULL,
                'last_name' => 'Dooley',
                'first_name' => 'Maggie',
                'date_of_birth' => '2023-02-05',
                'contact_number' => '973.358.9375',
                'email' => 'growe@example.net',
                'block_street' => '8542 Rempel Plains Apt. 792',
                'barangay' => 'ville',
                'city_or_municipality' => 'East Lavada',
                'social_media' => 'denesik.misty',
                'signature' => 'https://via.placeholder.com/640x480.png/005588?text=odio',
                'created_at' => '2024-06-28 09:20:04',
                'updated_at' => '2024-06-28 09:20:04',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'photo' => NULL,
                'last_name' => 'Gottlieb',
                'first_name' => 'Esther',
                'date_of_birth' => '2012-03-01',
                'contact_number' => '+1-843-694-6639',
                'email' => 'clehner@example.net',
                'block_street' => '100 Nicola Divide Apt. 360',
                'barangay' => 'view',
                'city_or_municipality' => 'Pfannerstillville',
                'social_media' => 'waylon65',
                'signature' => 'https://via.placeholder.com/640x480.png/006666?text=autem',
                'created_at' => '2024-06-28 09:20:04',
                'updated_at' => '2024-06-28 09:20:04',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'photo' => NULL,
                'last_name' => 'Kuhlman',
                'first_name' => 'Letha',
                'date_of_birth' => '1985-06-28',
                'contact_number' => '385.520.3289',
                'email' => 'christian.hill@example.com',
                'block_street' => '37706 Pablo Vista',
                'barangay' => 'side',
                'city_or_municipality' => 'North Abbyshire',
                'social_media' => 'jolie.lindgren',
                'signature' => 'https://via.placeholder.com/640x480.png/009988?text=modi',
                'created_at' => '2024-06-28 09:20:04',
                'updated_at' => '2024-06-28 09:20:04',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'photo' => NULL,
                'last_name' => 'Harris',
                'first_name' => 'Reginald',
                'date_of_birth' => '1995-03-03',
                'contact_number' => '+19544877558',
                'email' => 'lruecker@example.com',
                'block_street' => '3420 Kertzmann Roads Suite 331',
                'barangay' => 'haven',
                'city_or_municipality' => 'New Dameonchester',
                'social_media' => 'awitting',
                'signature' => 'https://via.placeholder.com/640x480.png/008844?text=libero',
                'created_at' => '2024-06-28 09:20:04',
                'updated_at' => '2024-06-28 09:20:04',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'photo' => NULL,
                'last_name' => 'Dietrich',
                'first_name' => 'Earnest',
                'date_of_birth' => '2016-01-31',
                'contact_number' => '+1.341.640.4859',
                'email' => 'dheathcote@example.net',
                'block_street' => '880 Casper Drive',
                'barangay' => 'chester',
                'city_or_municipality' => 'Port Naomichester',
                'social_media' => 'lonny.macejkovic',
                'signature' => 'https://via.placeholder.com/640x480.png/00aa22?text=nemo',
                'created_at' => '2024-06-28 09:20:04',
                'updated_at' => '2024-06-28 09:20:04',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'photo' => NULL,
                'last_name' => 'Cummerata',
                'first_name' => 'Wilbert',
                'date_of_birth' => '2014-06-03',
            'contact_number' => '+1 (931) 301-9342',
                'email' => 'rhea48@example.org',
                'block_street' => '869 Johnpaul Lights',
                'barangay' => 'ton',
                'city_or_municipality' => 'North Ashleigh',
                'social_media' => 'velva48',
                'signature' => 'https://via.placeholder.com/640x480.png/0066cc?text=labore',
                'created_at' => '2024-06-28 09:20:04',
                'updated_at' => '2024-06-28 09:20:04',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'photo' => NULL,
                'last_name' => 'Crona',
                'first_name' => 'Sage',
                'date_of_birth' => '1973-04-06',
                'contact_number' => '774.409.8404',
                'email' => 'estrella.rath@example.com',
                'block_street' => '8075 Larkin Walk Suite 959',
                'barangay' => 'port',
                'city_or_municipality' => 'Lake Adellchester',
                'social_media' => 'uschaden',
                'signature' => 'https://via.placeholder.com/640x480.png/00aa55?text=fugiat',
                'created_at' => '2024-06-28 09:20:04',
                'updated_at' => '2024-06-28 09:20:04',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'photo' => NULL,
                'last_name' => 'Schumm',
                'first_name' => 'Garrett',
                'date_of_birth' => '2024-01-04',
                'contact_number' => '407.218.4026',
                'email' => 'kattie24@example.com',
                'block_street' => '5297 Upton Shore Suite 934',
                'barangay' => 'town',
                'city_or_municipality' => 'South Reilly',
                'social_media' => 'neva.nader',
                'signature' => 'https://via.placeholder.com/640x480.png/00ddaa?text=animi',
                'created_at' => '2024-06-28 09:20:04',
                'updated_at' => '2024-06-28 09:20:04',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'photo' => NULL,
                'last_name' => 'Goodwin',
                'first_name' => 'Florida',
                'date_of_birth' => '2007-08-02',
                'contact_number' => '1-947-823-4275',
                'email' => 'brenden.lueilwitz@example.org',
                'block_street' => '3455 Cummerata Squares',
                'barangay' => 'borough',
                'city_or_municipality' => 'Zettaton',
                'social_media' => 'pacocha.marianna',
                'signature' => 'https://via.placeholder.com/640x480.png/0000aa?text=tempore',
                'created_at' => '2024-06-28 09:20:04',
                'updated_at' => '2024-06-28 09:20:04',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'photo' => NULL,
                'last_name' => 'Larkin',
                'first_name' => 'Austen',
                'date_of_birth' => '1975-11-07',
                'contact_number' => '832.724.7701',
                'email' => 'gtoy@example.com',
                'block_street' => '12821 Jaylin Ports',
                'barangay' => 'chester',
                'city_or_municipality' => 'New Christineberg',
                'social_media' => 'selina67',
                'signature' => 'https://via.placeholder.com/640x480.png/002211?text=et',
                'created_at' => '2024-06-28 09:20:04',
                'updated_at' => '2024-06-28 09:20:04',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'photo' => NULL,
                'last_name' => 'Ferry',
                'first_name' => 'Lucius',
                'date_of_birth' => '1983-12-14',
                'contact_number' => '217.787.6629',
                'email' => 'hansen.marie@example.net',
                'block_street' => '193 Cremin Rest Apt. 596',
                'barangay' => 'bury',
                'city_or_municipality' => 'Avisfurt',
                'social_media' => 'ekoepp',
                'signature' => 'https://via.placeholder.com/640x480.png/002266?text=doloribus',
                'created_at' => '2024-06-28 09:20:04',
                'updated_at' => '2024-06-28 09:20:04',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'photo' => NULL,
                'last_name' => 'Jones',
                'first_name' => 'Stanley',
                'date_of_birth' => '2022-10-12',
                'contact_number' => '406-596-4091',
                'email' => 'waino88@example.org',
                'block_street' => '5254 Goldner Viaduct',
                'barangay' => 'town',
                'city_or_municipality' => 'South Jane',
                'social_media' => 'kristoffer27',
                'signature' => 'https://via.placeholder.com/640x480.png/009988?text=consequuntur',
                'created_at' => '2024-06-28 09:20:04',
                'updated_at' => '2024-06-28 09:20:04',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'photo' => NULL,
                'last_name' => 'Schmidt',
                'first_name' => 'Vita',
                'date_of_birth' => '1974-08-05',
                'contact_number' => '1-818-708-0349',
                'email' => 'iprosacco@example.com',
                'block_street' => '4276 Lexi Extension Apt. 977',
                'barangay' => 'mouth',
                'city_or_municipality' => 'New Thelma',
                'social_media' => 'jaclyn84',
                'signature' => 'https://via.placeholder.com/640x480.png/00dd66?text=optio',
                'created_at' => '2024-06-28 09:20:04',
                'updated_at' => '2024-06-28 09:20:04',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'photo' => NULL,
                'last_name' => 'Lubowitz',
                'first_name' => 'Watson',
                'date_of_birth' => '2023-10-31',
            'contact_number' => '(234) 663-8297',
                'email' => 'orville.pfannerstill@example.com',
                'block_street' => '57026 Mitchell Route Apt. 959',
                'barangay' => 'fort',
                'city_or_municipality' => 'East Bretttown',
                'social_media' => 'rhoda.bashirian',
                'signature' => 'https://via.placeholder.com/640x480.png/009966?text=est',
                'created_at' => '2024-06-28 09:20:04',
                'updated_at' => '2024-06-28 09:20:04',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'photo' => NULL,
                'last_name' => 'Ziemann',
                'first_name' => 'Arvel',
                'date_of_birth' => '2022-02-17',
            'contact_number' => '(256) 935-7135',
                'email' => 'ernser.jeramy@example.net',
                'block_street' => '12226 Emma Manor Apt. 872',
                'barangay' => 'burgh',
                'city_or_municipality' => 'Manteborough',
                'social_media' => 'devyn61',
                'signature' => 'https://via.placeholder.com/640x480.png/007722?text=ut',
                'created_at' => '2024-06-28 09:20:04',
                'updated_at' => '2024-06-28 09:20:04',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'photo' => NULL,
                'last_name' => 'Schiller',
                'first_name' => 'Camryn',
                'date_of_birth' => '2000-06-24',
                'contact_number' => '+12814767905',
                'email' => 'carmella70@example.net',
                'block_street' => '731 Tony Street',
                'barangay' => 'side',
                'city_or_municipality' => 'Sauermouth',
                'social_media' => 'christine.robel',
                'signature' => 'https://via.placeholder.com/640x480.png/00eeee?text=aspernatur',
                'created_at' => '2024-06-28 09:20:04',
                'updated_at' => '2024-06-28 09:20:04',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'photo' => NULL,
                'last_name' => 'Lockman',
                'first_name' => 'Kristofer',
                'date_of_birth' => '1979-02-25',
                'contact_number' => '608-873-8231',
                'email' => 'kcorkery@example.net',
                'block_street' => '59059 Predovic Wells',
                'barangay' => 'town',
                'city_or_municipality' => 'Shanestad',
                'social_media' => 'zbergnaum',
                'signature' => 'https://via.placeholder.com/640x480.png/0000ee?text=doloremque',
                'created_at' => '2024-06-28 09:20:04',
                'updated_at' => '2024-06-28 09:20:04',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'photo' => NULL,
                'last_name' => 'Frami',
                'first_name' => 'Esperanza',
                'date_of_birth' => '2024-04-09',
                'contact_number' => '1-938-326-7987',
                'email' => 'wconroy@example.com',
                'block_street' => '1563 Lorenza Lock Suite 126',
                'barangay' => 'mouth',
                'city_or_municipality' => 'Rooseveltfort',
                'social_media' => 'pjacobi',
                'signature' => 'https://via.placeholder.com/640x480.png/0077cc?text=pariatur',
                'created_at' => '2024-06-28 09:20:04',
                'updated_at' => '2024-06-28 09:20:04',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'photo' => NULL,
                'last_name' => 'Cummings',
                'first_name' => 'Blair',
                'date_of_birth' => '1986-07-02',
                'contact_number' => '602-852-2685',
                'email' => 'cummings.sigmund@example.org',
                'block_street' => '7325 Nolan Unions Apt. 212',
                'barangay' => 'mouth',
                'city_or_municipality' => 'Lake Barrett',
                'social_media' => 'collier.nicolette',
                'signature' => 'https://via.placeholder.com/640x480.png/0088ee?text=ea',
                'created_at' => '2024-06-28 09:20:04',
                'updated_at' => '2024-06-28 09:20:04',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'photo' => NULL,
                'last_name' => 'Little',
                'first_name' => 'Lisa',
                'date_of_birth' => '1978-01-29',
                'contact_number' => '+1-650-919-1517',
                'email' => 'farrell.brenden@example.net',
                'block_street' => '20179 Don Crossing Apt. 775',
                'barangay' => 'berg',
                'city_or_municipality' => 'Zulaufport',
                'social_media' => 'sadie.koch',
                'signature' => 'https://via.placeholder.com/640x480.png/004400?text=enim',
                'created_at' => '2024-06-28 10:47:37',
                'updated_at' => '2024-06-28 10:47:37',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'photo' => NULL,
                'last_name' => 'Yundt',
                'first_name' => 'Elaina',
                'date_of_birth' => '1997-06-02',
                'contact_number' => '616.489.4632',
                'email' => 'reichert.brook@example.net',
                'block_street' => '7653 Felton Green Apt. 297',
                'barangay' => 'haven',
                'city_or_municipality' => 'Gladyceville',
                'social_media' => 'conn.norbert',
                'signature' => 'https://via.placeholder.com/640x480.png/0088ee?text=dolores',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'photo' => NULL,
                'last_name' => 'Labadie',
                'first_name' => 'Ralph',
                'date_of_birth' => '2010-09-13',
                'contact_number' => '+1-360-316-8358',
                'email' => 'guillermo.mitchell@example.net',
                'block_street' => '2634 Teagan Prairie Apt. 605',
                'barangay' => 'view',
                'city_or_municipality' => 'New Ashlyfurt',
                'social_media' => 'estella18',
                'signature' => 'https://via.placeholder.com/640x480.png/008811?text=ratione',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'photo' => NULL,
                'last_name' => 'Hansen',
                'first_name' => 'Litzy',
                'date_of_birth' => '1999-02-21',
                'contact_number' => '1-412-958-2797',
                'email' => 'antonietta.boyle@example.com',
                'block_street' => '605 Harvey Valley Apt. 100',
                'barangay' => 'bury',
                'city_or_municipality' => 'Flavietown',
                'social_media' => 'kkohler',
                'signature' => 'https://via.placeholder.com/640x480.png/000099?text=ad',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'photo' => NULL,
                'last_name' => 'Yundt',
                'first_name' => 'Chasity',
                'date_of_birth' => '1997-02-24',
                'contact_number' => '1-580-851-9917',
                'email' => 'oscar38@example.org',
                'block_street' => '150 Dickinson Trail Suite 427',
                'barangay' => 'town',
                'city_or_municipality' => 'East Marilou',
                'social_media' => 'ludwig.gusikowski',
                'signature' => 'https://via.placeholder.com/640x480.png/007744?text=ipsam',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'photo' => NULL,
                'last_name' => 'Jones',
                'first_name' => 'Alda',
                'date_of_birth' => '1995-01-03',
            'contact_number' => '(346) 505-7522',
                'email' => 'arden.zulauf@example.com',
                'block_street' => '97584 Schroeder Well',
                'barangay' => 'side',
                'city_or_municipality' => 'Lake Astrid',
                'social_media' => 'skiles.rosie',
                'signature' => 'https://via.placeholder.com/640x480.png/0077aa?text=autem',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'photo' => NULL,
                'last_name' => 'Heathcote',
                'first_name' => 'Mohammad',
                'date_of_birth' => '1988-07-16',
                'contact_number' => '808-880-9753',
                'email' => 'glover.lincoln@example.org',
                'block_street' => '2240 Fritsch Street',
                'barangay' => 'burgh',
                'city_or_municipality' => 'West Janiceshire',
                'social_media' => 'ryan.aleen',
                'signature' => 'https://via.placeholder.com/640x480.png/00ee88?text=autem',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'photo' => NULL,
                'last_name' => 'Jones',
                'first_name' => 'Kyla',
                'date_of_birth' => '2011-03-17',
                'contact_number' => '+16808025414',
                'email' => 'hwalker@example.org',
                'block_street' => '57495 Mabel Park',
                'barangay' => 'mouth',
                'city_or_municipality' => 'Leonieside',
                'social_media' => 'shaun07',
                'signature' => 'https://via.placeholder.com/640x480.png/001155?text=ut',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'photo' => NULL,
                'last_name' => 'Anderson',
                'first_name' => 'Laney',
                'date_of_birth' => '2018-06-10',
                'contact_number' => '425.620.8056',
                'email' => 'alvah.mayert@example.com',
                'block_street' => '679 Cartwright Avenue',
                'barangay' => 'town',
                'city_or_municipality' => 'Lake Samir',
                'social_media' => 'rodriguez.trace',
                'signature' => 'https://via.placeholder.com/640x480.png/0000ff?text=assumenda',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'photo' => NULL,
                'last_name' => 'Kris',
                'first_name' => 'Adriel',
                'date_of_birth' => '2014-06-13',
                'contact_number' => '+1-928-717-6316',
                'email' => 'emard.calista@example.net',
                'block_street' => '421 Jamie Throughway',
                'barangay' => 'mouth',
                'city_or_municipality' => 'North Selmermouth',
                'social_media' => 'morar.grady',
                'signature' => 'https://via.placeholder.com/640x480.png/004444?text=laboriosam',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'photo' => NULL,
                'last_name' => 'Hessel',
                'first_name' => 'Antonette',
                'date_of_birth' => '2019-01-21',
                'contact_number' => '+16519521595',
                'email' => 'josephine.ohara@example.net',
                'block_street' => '20405 Sabrina Street Apt. 472',
                'barangay' => 'berg',
                'city_or_municipality' => 'South Joanny',
                'social_media' => 'phoebe.gutmann',
                'signature' => 'https://via.placeholder.com/640x480.png/00cc33?text=voluptatem',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'photo' => NULL,
                'last_name' => 'Grimes',
                'first_name' => 'Rahul',
                'date_of_birth' => '2015-06-16',
                'contact_number' => '+1.786.374.9684',
                'email' => 'libby.hodkiewicz@example.com',
                'block_street' => '1849 Abbott Stream',
                'barangay' => 'chester',
                'city_or_municipality' => 'Rosamouth',
                'social_media' => 'ischowalter',
                'signature' => 'https://via.placeholder.com/640x480.png/009911?text=sit',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'photo' => NULL,
                'last_name' => 'Purdy',
                'first_name' => 'Dorothea',
                'date_of_birth' => '2013-04-20',
            'contact_number' => '+1 (330) 387-9613',
                'email' => 'christophe.boyer@example.com',
                'block_street' => '5633 Lang Expressway',
                'barangay' => 'stad',
                'city_or_municipality' => 'Woodrowville',
                'social_media' => 'lori16',
                'signature' => 'https://via.placeholder.com/640x480.png/003388?text=deleniti',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'photo' => NULL,
                'last_name' => 'Dibbert',
                'first_name' => 'Norene',
                'date_of_birth' => '2016-03-17',
                'contact_number' => '251-773-3328',
                'email' => 'quigley.alfonso@example.com',
                'block_street' => '938 Terence Common Suite 641',
                'barangay' => 'mouth',
                'city_or_municipality' => 'Altheahaven',
                'social_media' => 'howard27',
                'signature' => 'https://via.placeholder.com/640x480.png/0066cc?text=consectetur',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'photo' => NULL,
                'last_name' => 'Homenick',
                'first_name' => 'Cameron',
                'date_of_birth' => '1998-03-17',
            'contact_number' => '(662) 856-4747',
                'email' => 'earl.tremblay@example.com',
                'block_street' => '533 Darrion Rapid',
                'barangay' => 'haven',
                'city_or_municipality' => 'Floydview',
                'social_media' => 'dzboncak',
                'signature' => 'https://via.placeholder.com/640x480.png/00cc66?text=accusantium',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'photo' => NULL,
                'last_name' => 'Labadie',
                'first_name' => 'Paul',
                'date_of_birth' => '2020-03-01',
            'contact_number' => '+1 (260) 731-9672',
                'email' => 'emil.grant@example.net',
                'block_street' => '9082 Anderson Forges',
                'barangay' => 'berg',
                'city_or_municipality' => 'Port Moisesmouth',
                'social_media' => 'iraynor',
                'signature' => 'https://via.placeholder.com/640x480.png/00ffcc?text=repellendus',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'photo' => NULL,
                'last_name' => 'Grimes',
                'first_name' => 'Obie',
                'date_of_birth' => '2002-07-08',
                'contact_number' => '669.839.3084',
                'email' => 'lratke@example.org',
                'block_street' => '55567 Hand Forks Suite 843',
                'barangay' => 'ton',
                'city_or_municipality' => 'East Derickmouth',
                'social_media' => 'mark.kohler',
                'signature' => 'https://via.placeholder.com/640x480.png/00dd00?text=quasi',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'photo' => NULL,
                'last_name' => 'Schinner',
                'first_name' => 'Michael',
                'date_of_birth' => '1971-07-09',
                'contact_number' => '785-342-9098',
                'email' => 'mcglynn.estel@example.com',
                'block_street' => '6213 Fisher Bypass Apt. 217',
                'barangay' => 'mouth',
                'city_or_municipality' => 'Emmetmouth',
                'social_media' => 'ryan.mackenzie',
                'signature' => 'https://via.placeholder.com/640x480.png/0077ee?text=non',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'photo' => NULL,
                'last_name' => 'Russel',
                'first_name' => 'Nat',
                'date_of_birth' => '1991-10-11',
                'contact_number' => '1-813-499-7892',
                'email' => 'elsa01@example.com',
                'block_street' => '901 Hayley Cliff Apt. 668',
                'barangay' => 'fort',
                'city_or_municipality' => 'Christopview',
                'social_media' => 'emmerich.eleanora',
                'signature' => 'https://via.placeholder.com/640x480.png/007711?text=ut',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'photo' => NULL,
                'last_name' => 'Satterfield',
                'first_name' => 'Alyson',
                'date_of_birth' => '2004-07-18',
                'contact_number' => '930-838-4553',
                'email' => 'violet33@example.com',
                'block_street' => '66138 Lenny Valleys',
                'barangay' => 'berg',
                'city_or_municipality' => 'Port Pat',
                'social_media' => 'kkovacek',
                'signature' => 'https://via.placeholder.com/640x480.png/0099ee?text=qui',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'photo' => NULL,
                'last_name' => 'Goodwin',
                'first_name' => 'Chyna',
                'date_of_birth' => '2002-09-16',
            'contact_number' => '(234) 439-3258',
                'email' => 'malcolm.brekke@example.org',
                'block_street' => '5016 Jairo Bypass Apt. 314',
                'barangay' => 'stad',
                'city_or_municipality' => 'Schneiderview',
                'social_media' => 'kiera14',
                'signature' => 'https://via.placeholder.com/640x480.png/002299?text=quia',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'photo' => NULL,
                'last_name' => 'Kihn',
                'first_name' => 'Reilly',
                'date_of_birth' => '2020-11-14',
                'contact_number' => '352-930-7511',
                'email' => 'gbeatty@example.net',
                'block_street' => '8026 Rosemarie Pike',
                'barangay' => 'port',
                'city_or_municipality' => 'North Giovannyport',
                'social_media' => 'lenora92',
                'signature' => 'https://via.placeholder.com/640x480.png/00ccaa?text=asperiores',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'photo' => NULL,
                'last_name' => 'Okuneva',
                'first_name' => 'Flavie',
                'date_of_birth' => '2008-09-24',
                'contact_number' => '+1-740-605-5627',
                'email' => 'fbashirian@example.net',
                'block_street' => '73070 Leland Keys Apt. 657',
                'barangay' => 'borough',
                'city_or_municipality' => 'Erichview',
                'social_media' => 'brendon.kiehn',
                'signature' => 'https://via.placeholder.com/640x480.png/00aadd?text=et',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'photo' => NULL,
                'last_name' => 'Oberbrunner',
                'first_name' => 'Kenneth',
                'date_of_birth' => '1977-03-11',
                'contact_number' => '480.808.7083',
                'email' => 'ewest@example.net',
                'block_street' => '94803 Davis Mountain Suite 128',
                'barangay' => 'furt',
                'city_or_municipality' => 'New Elena',
                'social_media' => 'rohan.ottis',
                'signature' => 'https://via.placeholder.com/640x480.png/008866?text=ut',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'photo' => NULL,
                'last_name' => 'Walker',
                'first_name' => 'Elian',
                'date_of_birth' => '1976-10-17',
                'contact_number' => '626-902-0551',
                'email' => 'conn.celestine@example.net',
                'block_street' => '79970 Name Village',
                'barangay' => 'bury',
                'city_or_municipality' => 'New Alfonzoside',
                'social_media' => 'monty19',
                'signature' => 'https://via.placeholder.com/640x480.png/0044dd?text=ad',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'photo' => NULL,
                'last_name' => 'Doyle',
                'first_name' => 'Cathrine',
                'date_of_birth' => '1987-05-22',
                'contact_number' => '1-903-332-9275',
                'email' => 'amira68@example.org',
                'block_street' => '42139 Dawn Neck',
                'barangay' => 'side',
                'city_or_municipality' => 'Cecileberg',
                'social_media' => 'willms.dashawn',
                'signature' => 'https://via.placeholder.com/640x480.png/000044?text=sit',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'photo' => NULL,
                'last_name' => 'Dare',
                'first_name' => 'Bernadette',
                'date_of_birth' => '2006-12-29',
                'contact_number' => '+13362883219',
                'email' => 'athena.keebler@example.org',
                'block_street' => '589 Hahn Greens',
                'barangay' => 'fort',
                'city_or_municipality' => 'New Dorris',
                'social_media' => 'irobel',
                'signature' => 'https://via.placeholder.com/640x480.png/0000aa?text=possimus',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'photo' => NULL,
                'last_name' => 'Bins',
                'first_name' => 'Vilma',
                'date_of_birth' => '1974-09-18',
                'contact_number' => '+1-502-308-4295',
                'email' => 'hmueller@example.com',
                'block_street' => '451 Jacobi Island Suite 955',
                'barangay' => 'furt',
                'city_or_municipality' => 'South Randallport',
                'social_media' => 'adrian.huels',
                'signature' => 'https://via.placeholder.com/640x480.png/00eeee?text=tempore',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'photo' => NULL,
                'last_name' => 'Goldner',
                'first_name' => 'Kelly',
                'date_of_birth' => '1971-07-12',
                'contact_number' => '+1.445.306.3768',
                'email' => 'haag.neil@example.org',
                'block_street' => '423 Price Trail',
                'barangay' => 'view',
                'city_or_municipality' => 'Candiceland',
                'social_media' => 'dameon28',
                'signature' => 'https://via.placeholder.com/640x480.png/00ff11?text=inventore',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'photo' => NULL,
                'last_name' => 'Morissette',
                'first_name' => 'Lowell',
                'date_of_birth' => '1997-07-01',
            'contact_number' => '+1 (443) 373-3778',
                'email' => 'okuneva.alisa@example.com',
                'block_street' => '2654 Roselyn Prairie',
                'barangay' => 'mouth',
                'city_or_municipality' => 'Lake Danteview',
                'social_media' => 'rey.johnson',
                'signature' => 'https://via.placeholder.com/640x480.png/00aabb?text=corporis',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'photo' => NULL,
                'last_name' => 'Murphy',
                'first_name' => 'Evan',
                'date_of_birth' => '2005-05-15',
            'contact_number' => '+1 (571) 443-2430',
                'email' => 'tswift@example.org',
                'block_street' => '606 Alexandrine Circle',
                'barangay' => 'berg',
                'city_or_municipality' => 'West Jane',
                'social_media' => 'addie.ortiz',
                'signature' => 'https://via.placeholder.com/640x480.png/000066?text=voluptatum',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'photo' => NULL,
                'last_name' => 'Olson',
                'first_name' => 'Rosamond',
                'date_of_birth' => '1983-02-20',
                'contact_number' => '240-880-2506',
                'email' => 'valentin.kessler@example.net',
                'block_street' => '376 Effertz Avenue',
                'barangay' => 'port',
                'city_or_municipality' => 'Gottliebland',
                'social_media' => 'ashlynn28',
                'signature' => 'https://via.placeholder.com/640x480.png/00aaff?text=modi',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'photo' => NULL,
                'last_name' => 'Vandervort',
                'first_name' => 'Timmothy',
                'date_of_birth' => '2023-10-16',
                'contact_number' => '+1.309.572.9490',
                'email' => 'murray73@example.net',
                'block_street' => '9660 Murray Landing',
                'barangay' => 'stad',
                'city_or_municipality' => 'South Selina',
                'social_media' => 'von.kathleen',
                'signature' => 'https://via.placeholder.com/640x480.png/0055aa?text=nobis',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'photo' => NULL,
                'last_name' => 'Becker',
                'first_name' => 'Verona',
                'date_of_birth' => '1987-03-03',
                'contact_number' => '+1-219-334-0523',
                'email' => 'walton40@example.net',
                'block_street' => '7233 Jakubowski Centers Suite 193',
                'barangay' => 'land',
                'city_or_municipality' => 'Eulaliaport',
                'social_media' => 'erwin.mcglynn',
                'signature' => 'https://via.placeholder.com/640x480.png/0055bb?text=quos',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'photo' => NULL,
                'last_name' => 'Hamill',
                'first_name' => 'Ephraim',
                'date_of_birth' => '1993-09-13',
                'contact_number' => '458-418-3742',
                'email' => 'glover.asia@example.com',
                'block_street' => '3300 Ricardo Prairie',
                'barangay' => 'furt',
                'city_or_municipality' => 'New Brianaborough',
                'social_media' => 'madge.king',
                'signature' => 'https://via.placeholder.com/640x480.png/006699?text=nisi',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'photo' => NULL,
                'last_name' => 'Kshlerin',
                'first_name' => 'Gilberto',
                'date_of_birth' => '2014-12-18',
                'contact_number' => '580.868.4425',
                'email' => 'rolfson.kaden@example.org',
                'block_street' => '8714 Leanna Street',
                'barangay' => 'port',
                'city_or_municipality' => 'Rauberg',
                'social_media' => 'arno47',
                'signature' => 'https://via.placeholder.com/640x480.png/00ccee?text=impedit',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'photo' => NULL,
                'last_name' => 'Rohan',
                'first_name' => 'Vita',
                'date_of_birth' => '2002-07-24',
                'contact_number' => '708-250-1563',
                'email' => 'pascale.casper@example.net',
                'block_street' => '2176 Hoeger Hills',
                'barangay' => 'fort',
                'city_or_municipality' => 'Lake Arnoldmouth',
                'social_media' => 'gottlieb.zechariah',
                'signature' => 'https://via.placeholder.com/640x480.png/001122?text=sint',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'photo' => NULL,
                'last_name' => 'Harvey',
                'first_name' => 'Chadrick',
                'date_of_birth' => '1995-02-28',
                'contact_number' => '+1.484.702.7248',
                'email' => 'william99@example.com',
                'block_street' => '73329 Lyric Corners',
                'barangay' => 'port',
                'city_or_municipality' => 'Jerdestad',
                'social_media' => 'albert.medhurst',
                'signature' => 'https://via.placeholder.com/640x480.png/0066bb?text=iusto',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'photo' => NULL,
                'last_name' => 'Langosh',
                'first_name' => 'Donnie',
                'date_of_birth' => '2019-05-28',
                'contact_number' => '+1-229-840-4188',
                'email' => 'gferry@example.net',
                'block_street' => '83527 Autumn Track Apt. 765',
                'barangay' => 'furt',
                'city_or_municipality' => 'East Wendyport',
                'social_media' => 'abshire.eriberto',
                'signature' => 'https://via.placeholder.com/640x480.png/008855?text=repellendus',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'photo' => NULL,
                'last_name' => 'Miller',
                'first_name' => 'Theresia',
                'date_of_birth' => '1997-12-22',
            'contact_number' => '(779) 619-2103',
                'email' => 'mitchell.harber@example.com',
                'block_street' => '207 Rodriguez Rapid',
                'barangay' => 'side',
                'city_or_municipality' => 'Torreyville',
                'social_media' => 'towne.kayley',
                'signature' => 'https://via.placeholder.com/640x480.png/0000dd?text=cum',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'photo' => NULL,
                'last_name' => 'Blanda',
                'first_name' => 'Astrid',
                'date_of_birth' => '1999-01-20',
                'contact_number' => '1-949-341-8411',
                'email' => 'hanna84@example.org',
                'block_street' => '72681 Steuber Islands Apt. 207',
                'barangay' => 'mouth',
                'city_or_municipality' => 'Maynardview',
                'social_media' => 'abelardo28',
                'signature' => 'https://via.placeholder.com/640x480.png/006622?text=omnis',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'photo' => NULL,
                'last_name' => 'Schroeder',
                'first_name' => 'Winona',
                'date_of_birth' => '2019-01-05',
                'contact_number' => '+1.408.716.2242',
                'email' => 'price.lavada@example.com',
                'block_street' => '78049 Lauriane Rest',
                'barangay' => 'bury',
                'city_or_municipality' => 'Leannonview',
                'social_media' => 'mathias10',
                'signature' => 'https://via.placeholder.com/640x480.png/00bbaa?text=aut',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'photo' => NULL,
                'last_name' => 'Collins',
                'first_name' => 'Daron',
                'date_of_birth' => '1987-03-29',
                'contact_number' => '854.541.6880',
                'email' => 'darby.jaskolski@example.net',
                'block_street' => '88448 O\'Reilly Junction Apt. 043',
                'barangay' => 'land',
                'city_or_municipality' => 'Stokesville',
                'social_media' => 'domenico21',
                'signature' => 'https://via.placeholder.com/640x480.png/0011aa?text=voluptates',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'photo' => NULL,
                'last_name' => 'Hamill',
                'first_name' => 'Hermina',
                'date_of_birth' => '1996-10-07',
                'contact_number' => '+17272596881',
                'email' => 'schinner.dorian@example.org',
                'block_street' => '93726 Nathanael Shores Suite 016',
                'barangay' => 'chester',
                'city_or_municipality' => 'Yasmineview',
                'social_media' => 'chloe.mcdermott',
                'signature' => 'https://via.placeholder.com/640x480.png/00dd55?text=cumque',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'photo' => NULL,
                'last_name' => 'Raynor',
                'first_name' => 'Kayla',
                'date_of_birth' => '1999-07-22',
                'contact_number' => '+1-828-608-1860',
                'email' => 'rosella48@example.org',
                'block_street' => '4879 Fanny Prairie',
                'barangay' => 'fort',
                'city_or_municipality' => 'Gradyshire',
                'social_media' => 'halie.kreiger',
                'signature' => 'https://via.placeholder.com/640x480.png/0066bb?text=voluptas',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'photo' => NULL,
                'last_name' => 'Osinski',
                'first_name' => 'Jazmyn',
                'date_of_birth' => '2024-01-25',
                'contact_number' => '+19517623479',
                'email' => 'darwin.oconnell@example.net',
                'block_street' => '6509 Klein Village Apt. 191',
                'barangay' => 'fort',
                'city_or_municipality' => 'New Zackery',
                'social_media' => 'derrick.tromp',
                'signature' => 'https://via.placeholder.com/640x480.png/004477?text=quia',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'photo' => NULL,
                'last_name' => 'Koepp',
                'first_name' => 'Frida',
                'date_of_birth' => '1993-11-12',
                'contact_number' => '+1-256-316-2997',
                'email' => 'xjakubowski@example.net',
                'block_street' => '23048 Nolan Village',
                'barangay' => 'mouth',
                'city_or_municipality' => 'Hannafurt',
                'social_media' => 'christy.spinka',
                'signature' => 'https://via.placeholder.com/640x480.png/0055cc?text=quod',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'photo' => NULL,
                'last_name' => 'Rau',
                'first_name' => 'Bernhard',
                'date_of_birth' => '1971-10-30',
            'contact_number' => '(442) 957-1617',
                'email' => 'iswift@example.net',
                'block_street' => '879 Stehr Mills Suite 161',
                'barangay' => 'side',
                'city_or_municipality' => 'Ahmedstad',
                'social_media' => 'zechariah.lowe',
                'signature' => 'https://via.placeholder.com/640x480.png/0044cc?text=quasi',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'photo' => NULL,
                'last_name' => 'Windler',
                'first_name' => 'Reba',
                'date_of_birth' => '1985-12-30',
            'contact_number' => '(478) 733-8178',
                'email' => 'haylie75@example.org',
                'block_street' => '3154 Pfeffer Unions Suite 535',
                'barangay' => 'haven',
                'city_or_municipality' => 'Lake Mariana',
                'social_media' => 'gframi',
                'signature' => 'https://via.placeholder.com/640x480.png/0066cc?text=quis',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'photo' => NULL,
                'last_name' => 'Wuckert',
                'first_name' => 'Luz',
                'date_of_birth' => '2013-06-23',
            'contact_number' => '(828) 259-2753',
                'email' => 'walter20@example.com',
                'block_street' => '1886 Casandra Lane',
                'barangay' => 'chester',
                'city_or_municipality' => 'Oceaneberg',
                'social_media' => 'ogerhold',
                'signature' => 'https://via.placeholder.com/640x480.png/0066dd?text=iusto',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'photo' => NULL,
                'last_name' => 'Larkin',
                'first_name' => 'Isaac',
                'date_of_birth' => '2018-03-24',
            'contact_number' => '(707) 674-3127',
                'email' => 'grady.may@example.org',
                'block_street' => '8744 Jaylan Crest Apt. 347',
                'barangay' => 'haven',
                'city_or_municipality' => 'North Edgardo',
                'social_media' => 'jefferey.hamill',
                'signature' => 'https://via.placeholder.com/640x480.png/00ffdd?text=minima',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'photo' => NULL,
                'last_name' => 'Fay',
                'first_name' => 'Nella',
                'date_of_birth' => '2023-01-23',
                'contact_number' => '+1-530-462-1222',
                'email' => 'wilfrid.armstrong@example.net',
                'block_street' => '7004 Kreiger Corner',
                'barangay' => 'borough',
                'city_or_municipality' => 'North Jessieland',
                'social_media' => 'rossie.stehr',
                'signature' => 'https://via.placeholder.com/640x480.png/00ccdd?text=veniam',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'photo' => NULL,
                'last_name' => 'Bruen',
                'first_name' => 'Kennith',
                'date_of_birth' => '2011-11-28',
            'contact_number' => '(786) 397-0562',
                'email' => 'idouglas@example.org',
                'block_street' => '196 Quigley Mission',
                'barangay' => 'mouth',
                'city_or_municipality' => 'Port Jaiden',
                'social_media' => 'mabshire',
                'signature' => 'https://via.placeholder.com/640x480.png/00bb88?text=consequatur',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'photo' => NULL,
                'last_name' => 'Wolff',
                'first_name' => 'Dejon',
                'date_of_birth' => '2016-06-07',
                'contact_number' => '+13089773160',
                'email' => 'wehner.haylee@example.com',
                'block_street' => '709 Price Manor Apt. 462',
                'barangay' => 'chester',
                'city_or_municipality' => 'Einomouth',
                'social_media' => 'buddy.langosh',
                'signature' => 'https://via.placeholder.com/640x480.png/0044dd?text=tempore',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'photo' => NULL,
                'last_name' => 'McDermott',
                'first_name' => 'Pearl',
                'date_of_birth' => '1975-11-02',
                'contact_number' => '+13804623324',
                'email' => 'kromaguera@example.net',
                'block_street' => '9175 Bartell Walks',
                'barangay' => 'ton',
                'city_or_municipality' => 'South Malcolm',
                'social_media' => 'gtoy',
                'signature' => 'https://via.placeholder.com/640x480.png/00bbcc?text=dolorum',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'photo' => NULL,
                'last_name' => 'Hessel',
                'first_name' => 'Jennings',
                'date_of_birth' => '1994-05-23',
                'contact_number' => '407.327.4824',
                'email' => 'kuphal.tyrique@example.net',
                'block_street' => '577 Kassandra Canyon Apt. 065',
                'barangay' => 'furt',
                'city_or_municipality' => 'Boscoland',
                'social_media' => 'ldaugherty',
                'signature' => 'https://via.placeholder.com/640x480.png/004400?text=doloribus',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'photo' => NULL,
                'last_name' => 'Conn',
                'first_name' => 'Liam',
                'date_of_birth' => '2007-04-02',
                'contact_number' => '681.795.6787',
                'email' => 'colby.marvin@example.org',
                'block_street' => '2209 Toby Curve',
                'barangay' => 'burgh',
                'city_or_municipality' => 'Connerhaven',
                'social_media' => 'heidenreich.sofia',
                'signature' => 'https://via.placeholder.com/640x480.png/00cc11?text=alias',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'photo' => NULL,
                'last_name' => 'Botsford',
                'first_name' => 'Claud',
                'date_of_birth' => '1980-03-17',
            'contact_number' => '(240) 367-3605',
                'email' => 'hjast@example.com',
                'block_street' => '465 Salvatore Villages Apt. 515',
                'barangay' => 'furt',
                'city_or_municipality' => 'West Winfieldland',
                'social_media' => 'florencio.schumm',
                'signature' => 'https://via.placeholder.com/640x480.png/008844?text=impedit',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'photo' => NULL,
                'last_name' => 'Hermann',
                'first_name' => 'Reynold',
                'date_of_birth' => '2006-06-30',
                'contact_number' => '+1-689-809-3918',
                'email' => 'darwin.kovacek@example.org',
                'block_street' => '23929 Bernier Valleys',
                'barangay' => 'mouth',
                'city_or_municipality' => 'Trinityfurt',
                'social_media' => 'wyman.cornell',
                'signature' => 'https://via.placeholder.com/640x480.png/00cc77?text=nihil',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'photo' => NULL,
                'last_name' => 'Feeney',
                'first_name' => 'Queen',
                'date_of_birth' => '1999-02-23',
                'contact_number' => '667.916.9731',
                'email' => 'egleichner@example.org',
                'block_street' => '195 Albert Divide',
                'barangay' => 'furt',
                'city_or_municipality' => 'Port Keith',
                'social_media' => 'koss.johnny',
                'signature' => 'https://via.placeholder.com/640x480.png/00ee11?text=nulla',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'photo' => NULL,
                'last_name' => 'Von',
                'first_name' => 'Heloise',
                'date_of_birth' => '1983-07-25',
                'contact_number' => '+1-747-248-3054',
                'email' => 'hazle37@example.com',
                'block_street' => '695 Ada Squares',
                'barangay' => 'stad',
                'city_or_municipality' => 'New Abbigailchester',
                'social_media' => 'heath.kling',
                'signature' => 'https://via.placeholder.com/640x480.png/0033bb?text=alias',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'photo' => NULL,
                'last_name' => 'Prosacco',
                'first_name' => 'Ryley',
                'date_of_birth' => '1984-02-17',
                'contact_number' => '+1-865-823-7621',
                'email' => 'kaitlyn.stracke@example.net',
                'block_street' => '66475 Monserrate Plains Suite 392',
                'barangay' => 'berg',
                'city_or_municipality' => 'New Johnnie',
                'social_media' => 'sister.toy',
                'signature' => 'https://via.placeholder.com/640x480.png/009955?text=corporis',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'photo' => NULL,
                'last_name' => 'Moore',
                'first_name' => 'Lula',
                'date_of_birth' => '2007-12-22',
            'contact_number' => '(774) 349-6048',
                'email' => 'tsanford@example.com',
                'block_street' => '17747 Aniya Cape Suite 230',
                'barangay' => 'stad',
                'city_or_municipality' => 'Georgiannaside',
                'social_media' => 'qcasper',
                'signature' => 'https://via.placeholder.com/640x480.png/0044dd?text=dolorem',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'photo' => NULL,
                'last_name' => 'Deckow',
                'first_name' => 'Mae',
                'date_of_birth' => '2000-05-24',
                'contact_number' => '1-412-785-0506',
                'email' => 'susana12@example.net',
                'block_street' => '2738 Orn Freeway Apt. 343',
                'barangay' => 'shire',
                'city_or_municipality' => 'Andreaneborough',
                'social_media' => 'rutherford.salma',
                'signature' => 'https://via.placeholder.com/640x480.png/00bb44?text=assumenda',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'photo' => NULL,
                'last_name' => 'Torphy',
                'first_name' => 'Earnestine',
                'date_of_birth' => '2002-03-08',
                'contact_number' => '310.513.0508',
                'email' => 'emelia.robel@example.org',
                'block_street' => '466 Harvey Summit',
                'barangay' => 'shire',
                'city_or_municipality' => 'East Denis',
                'social_media' => 'aurore.kuvalis',
                'signature' => 'https://via.placeholder.com/640x480.png/001111?text=aut',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'photo' => NULL,
                'last_name' => 'West',
                'first_name' => 'Asha',
                'date_of_birth' => '2011-10-07',
            'contact_number' => '(405) 969-4755',
                'email' => 'sister.cartwright@example.org',
                'block_street' => '76465 Heidenreich Crossroad Apt. 802',
                'barangay' => 'port',
                'city_or_municipality' => 'Fletashire',
                'social_media' => 'streich.gretchen',
                'signature' => 'https://via.placeholder.com/640x480.png/0000aa?text=nesciunt',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'photo' => NULL,
                'last_name' => 'Corkery',
                'first_name' => 'Nicola',
                'date_of_birth' => '2024-01-29',
                'contact_number' => '754.259.6503',
                'email' => 'carroll.caitlyn@example.net',
                'block_street' => '3964 Jamarcus Port',
                'barangay' => 'bury',
                'city_or_municipality' => 'Gerholdville',
                'social_media' => 'zreichert',
                'signature' => 'https://via.placeholder.com/640x480.png/00aa88?text=non',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'photo' => NULL,
                'last_name' => 'Simonis',
                'first_name' => 'Bette',
                'date_of_birth' => '1977-11-21',
                'contact_number' => '1-586-796-8098',
                'email' => 'sweber@example.org',
                'block_street' => '260 Reichel Glen Suite 921',
                'barangay' => 'fort',
                'city_or_municipality' => 'South Hulda',
                'social_media' => 'willis65',
                'signature' => 'https://via.placeholder.com/640x480.png/0044cc?text=sapiente',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'photo' => NULL,
                'last_name' => 'Russel',
                'first_name' => 'Alaina',
                'date_of_birth' => '1977-05-01',
            'contact_number' => '+1 (605) 591-5155',
                'email' => 'deanna81@example.com',
                'block_street' => '4755 Goyette Junctions Suite 890',
                'barangay' => 'furt',
                'city_or_municipality' => 'Daughertyland',
                'social_media' => 'junior55',
                'signature' => 'https://via.placeholder.com/640x480.png/0011cc?text=ab',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'photo' => NULL,
                'last_name' => 'Flatley',
                'first_name' => 'Ulises',
                'date_of_birth' => '1989-09-10',
                'contact_number' => '+1-281-853-7984',
                'email' => 'magali72@example.com',
                'block_street' => '340 Schuppe Inlet Suite 095',
                'barangay' => 'burgh',
                'city_or_municipality' => 'Keelingview',
                'social_media' => 'margret30',
                'signature' => 'https://via.placeholder.com/640x480.png/008866?text=soluta',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'photo' => NULL,
                'last_name' => 'Buckridge',
                'first_name' => 'Doyle',
                'date_of_birth' => '2010-01-23',
                'contact_number' => '+1.706.551.8296',
                'email' => 'philip63@example.net',
                'block_street' => '19972 Madelyn Keys',
                'barangay' => 'bury',
                'city_or_municipality' => 'Braunton',
                'social_media' => 'laurie.bartell',
                'signature' => 'https://via.placeholder.com/640x480.png/003355?text=cupiditate',
                'created_at' => '2024-06-28 10:47:38',
                'updated_at' => '2024-06-28 10:47:38',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}