<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menus')->delete();
        
        \DB::table('menus')->insert(array (
            0 => 
            array (
                'id' => 1,
                'label' => 'Menus',
                'icon' => 'la la-list',
                'url' => 'menu',
                'permissions' => '["menus_list"]',
                'parent_id' => 13,
                'lft' => 81,
                'rgt' => 82,
                'depth' => 2,
                'created_at' => '2024-06-30 16:29:49',
                'updated_at' => '2024-07-27 12:56:48',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'label' => 'Accounts',
                'icon' => 'las la-list',
                'url' => 'account',
                'permissions' => '["accounts_list"]',
                'parent_id' => NULL,
                'lft' => 8,
                'rgt' => 9,
                'depth' => 1,
                'created_at' => '2024-06-30 16:36:03',
                'updated_at' => '2024-07-27 12:56:48',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'label' => 'Billings',
                'icon' => 'las la-file-invoice',
                'url' => 'billing',
                'permissions' => '["billings_list"]',
                'parent_id' => 40,
                'lft' => 11,
                'rgt' => 12,
                'depth' => 2,
                'created_at' => '2024-06-30 16:50:13',
                'updated_at' => '2024-07-27 12:56:48',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'label' => 'Customers',
                'icon' => 'las la-user-tie',
                'url' => 'customer',
                'permissions' => '["customers_list"]',
                'parent_id' => NULL,
                'lft' => 6,
                'rgt' => 7,
                'depth' => 1,
                'created_at' => '2024-06-30 16:50:34',
                'updated_at' => '2024-07-27 12:56:48',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'label' => 'Planned Applications',
                'icon' => 'las la-business-time',
                'url' => 'planned-application',
                'permissions' => '["planned_applications_list"]',
                'parent_id' => NULL,
                'lft' => 58,
                'rgt' => 59,
                'depth' => 1,
                'created_at' => '2024-06-30 16:51:15',
                'updated_at' => '2024-07-27 12:56:48',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'label' => 'APP Settings',
                'icon' => NULL,
                'url' => NULL,
                'permissions' => '["menu_separator_app_settings"]',
                'parent_id' => NULL,
                'lft' => 42,
                'rgt' => 43,
                'depth' => 1,
                'created_at' => '2024-06-30 16:52:54',
                'updated_at' => '2024-07-27 12:56:48',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'label' => 'Account Statuses',
                'icon' => 'las la-rss',
                'url' => 'account-status',
                'permissions' => '["account_statuses_list"]',
                'parent_id' => NULL,
                'lft' => 52,
                'rgt' => 53,
                'depth' => 1,
                'created_at' => '2024-06-30 16:54:18',
                'updated_at' => '2024-07-27 12:56:48',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'label' => 'Locations',
                'icon' => 'las la-map-marked',
                'url' => 'location',
                'permissions' => '["locations_list"]',
                'parent_id' => NULL,
                'lft' => 48,
                'rgt' => 49,
                'depth' => 1,
                'created_at' => '2024-06-30 16:54:37',
                'updated_at' => '2024-07-27 12:56:48',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'label' => 'Subscriptions',
                'icon' => 'lab la-youtube',
                'url' => 'subscription',
                'permissions' => '["subscriptions_list"]',
                'parent_id' => NULL,
                'lft' => 50,
                'rgt' => 51,
                'depth' => 1,
                'created_at' => '2024-06-30 16:55:33',
                'updated_at' => '2024-07-27 12:56:48',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'label' => 'One-Time Charges',
                'icon' => 'las la-money-bill-alt',
                'url' => 'otc',
                'permissions' => '["otcs_list"]',
                'parent_id' => NULL,
                'lft' => 54,
                'rgt' => 55,
                'depth' => 1,
                'created_at' => '2024-06-30 16:56:00',
                'updated_at' => '2024-07-27 12:56:48',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'label' => 'Contract Periods',
                'icon' => 'las la-file-contract',
                'url' => 'contract-period',
                'permissions' => '["contract_periods_list"]',
                'parent_id' => NULL,
                'lft' => 56,
                'rgt' => 57,
                'depth' => 1,
                'created_at' => '2024-06-30 16:57:41',
                'updated_at' => '2024-07-27 12:56:48',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'label' => 'Planned App. Types',
                'icon' => 'las la-briefcase',
                'url' => 'planned-application-type',
                'permissions' => '["planned_application_types_list"]',
                'parent_id' => NULL,
                'lft' => 60,
                'rgt' => 61,
                'depth' => 1,
                'created_at' => '2024-06-30 16:58:06',
                'updated_at' => '2024-07-27 12:56:48',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'label' => 'Admin Only',
                'icon' => 'la la-puzzle-piece',
                'url' => NULL,
                'permissions' => NULL,
                'parent_id' => NULL,
                'lft' => 62,
                'rgt' => 83,
                'depth' => 1,
                'created_at' => '2024-06-30 17:08:32',
                'updated_at' => '2024-07-27 12:56:48',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'label' => 'Authentication',
                'icon' => NULL,
                'url' => NULL,
                'permissions' => NULL,
                'parent_id' => 13,
                'lft' => 63,
                'rgt' => 64,
                'depth' => 2,
                'created_at' => '2024-06-30 17:10:43',
                'updated_at' => '2024-07-27 12:56:48',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'label' => 'Users',
                'icon' => 'la la-user',
                'url' => 'user',
                'permissions' => '["users_list"]',
                'parent_id' => 13,
                'lft' => 65,
                'rgt' => 66,
                'depth' => 2,
                'created_at' => '2024-06-30 17:11:54',
                'updated_at' => '2024-07-27 12:56:48',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'label' => 'Roles',
                'icon' => 'la la-group',
                'url' => 'role',
                'permissions' => '["roles_list"]',
                'parent_id' => 13,
                'lft' => 67,
                'rgt' => 68,
                'depth' => 2,
                'created_at' => '2024-06-30 17:14:39',
                'updated_at' => '2024-07-27 12:56:48',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'label' => 'Permissions',
                'icon' => 'la la-key',
                'url' => 'permission',
                'permissions' => '["permissions_list"]',
                'parent_id' => 13,
                'lft' => 69,
                'rgt' => 70,
                'depth' => 2,
                'created_at' => '2024-06-30 17:14:58',
                'updated_at' => '2024-07-27 12:56:48',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'label' => 'Tools',
                'icon' => NULL,
                'url' => NULL,
                'permissions' => NULL,
                'parent_id' => 13,
                'lft' => 71,
                'rgt' => 72,
                'depth' => 2,
                'created_at' => '2024-06-30 17:15:46',
                'updated_at' => '2024-07-27 12:56:48',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'label' => 'Backups',
                'icon' => 'la la-hdd-o',
                'url' => 'backup',
                'permissions' => '["admin_backups"]',
                'parent_id' => 13,
                'lft' => 73,
                'rgt' => 74,
                'depth' => 2,
                'created_at' => '2024-06-30 17:18:30',
                'updated_at' => '2024-07-27 12:56:48',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'label' => 'File Manager',
                'icon' => 'la la-files-o',
                'url' => 'elfinder',
                'permissions' => '["admin_file_manager"]',
                'parent_id' => 13,
                'lft' => 75,
                'rgt' => 76,
                'depth' => 2,
                'created_at' => '2024-06-30 17:19:32',
                'updated_at' => '2024-07-27 12:56:48',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'label' => 'Logs',
                'icon' => 'la la-terminal',
                'url' => 'log',
                'permissions' => '["admin_logs"]',
                'parent_id' => 13,
                'lft' => 77,
                'rgt' => 78,
                'depth' => 2,
                'created_at' => '2024-06-30 17:20:15',
                'updated_at' => '2024-07-27 12:56:48',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'label' => 'Activity Logs',
                'icon' => 'la la-stream',
                'url' => 'activity-log',
                'permissions' => '["admin_activity_logs"]',
                'parent_id' => 13,
                'lft' => 79,
                'rgt' => 80,
                'depth' => 2,
                'created_at' => '2024-06-30 17:21:06',
                'updated_at' => '2024-07-27 12:56:48',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'label' => 'Dashboard',
                'icon' => 'la la-home nav-icon',
                'url' => 'dashboard',
                'permissions' => NULL,
                'parent_id' => NULL,
                'lft' => 2,
                'rgt' => 3,
                'depth' => 1,
                'created_at' => '2024-06-30 18:52:42',
                'updated_at' => '2024-07-27 12:56:48',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'label' => 'Service Interruptions',
                'icon' => 'las la-exclamation-triangle',
                'url' => 'account-service-interruption',
                'permissions' => '["account_service_interruptions_list"]',
                'parent_id' => NULL,
                'lft' => 28,
                'rgt' => 29,
                'depth' => 1,
                'created_at' => '2024-07-01 18:18:55',
                'updated_at' => '2024-07-27 12:56:48',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'label' => 'Account Credits',
                'icon' => 'las la-money-bill-wave',
                'url' => 'account-credit',
                'permissions' => '["account_credits_list"]',
                'parent_id' => NULL,
                'lft' => 26,
                'rgt' => 27,
                'depth' => 1,
                'created_at' => '2024-07-03 09:38:06',
                'updated_at' => '2024-07-27 12:56:48',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'label' => 'Settings',
                'icon' => 'la la-cog',
                'url' => 'setting',
                'permissions' => '["settings_list"]',
                'parent_id' => NULL,
                'lft' => 44,
                'rgt' => 45,
                'depth' => 1,
                'created_at' => '2024-07-14 08:09:22',
                'updated_at' => '2024-07-27 12:56:48',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'label' => 'Community Strings',
                'icon' => 'las la-key',
                'url' => 'community-string',
                'permissions' => '["community_strings_list"]',
                'parent_id' => 28,
                'lft' => 39,
                'rgt' => 40,
                'depth' => 2,
                'created_at' => '2024-07-26 18:47:57',
                'updated_at' => '2024-07-27 12:56:48',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'label' => 'SNMP',
                'icon' => 'las la-user-secret',
                'url' => NULL,
                'permissions' => NULL,
                'parent_id' => NULL,
                'lft' => 36,
                'rgt' => 41,
                'depth' => 1,
                'created_at' => '2024-07-26 18:50:06',
                'updated_at' => '2024-07-27 12:56:48',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'label' => 'OLT Devices',
                'icon' => 'las la-stream',
                'url' => 'olts',
                'permissions' => '["olts_list"]',
                'parent_id' => 28,
                'lft' => 37,
                'rgt' => 38,
                'depth' => 2,
                'created_at' => '2024-07-26 19:31:10',
                'updated_at' => '2024-07-27 12:56:48',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'label' => 'Raisepon2 Controller',
                'icon' => 'las la-network-wired',
                'url' => 'raisepon2',
                'permissions' => '["raisepon2s_list"]',
                'parent_id' => NULL,
                'lft' => 34,
                'rgt' => 35,
                'depth' => 1,
                'created_at' => '2024-07-27 12:56:37',
                'updated_at' => '2024-07-27 12:56:48',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'label' => 'Notifications',
                'icon' => 'las la-bell',
                'url' => 'notification',
                'permissions' => '["notifications_list"]',
                'parent_id' => NULL,
                'lft' => 4,
                'rgt' => 5,
                'depth' => 1,
                'created_at' => '2024-07-29 16:36:07',
                'updated_at' => '2024-07-29 21:58:59',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'label' => 'Billing Groupings',
                'icon' => 'las la-tasks',
                'url' => 'billing-grouping',
                'permissions' => '["billing_groupings_list"]',
                'parent_id' => NULL,
                'lft' => 32,
                'rgt' => 33,
                'depth' => 1,
                'created_at' => '2024-08-08 12:04:54',
                'updated_at' => '2024-08-08 12:04:54',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'label' => 'Assign Collectors',
                'icon' => 'las la-user-tie',
                'url' => 'piso-wifi-collector',
                'permissions' => '["piso_wifi_collectors_list"]',
                'parent_id' => NULL,
                'lft' => 24,
                'rgt' => 25,
                'depth' => 1,
                'created_at' => '2024-08-13 18:19:00',
                'updated_at' => '2024-08-15 22:28:23',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'label' => 'WiFi Services',
                'icon' => 'las la-wifi',
                'url' => NULL,
                'permissions' => NULL,
                'parent_id' => NULL,
                'lft' => 22,
                'rgt' => 23,
                'depth' => 1,
                'created_at' => '2024-08-14 16:12:56',
                'updated_at' => '2024-08-14 16:12:56',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'label' => 'Wifi harvests',
                'icon' => 'las la-hand-holding-usd',
                'url' => 'wifi-harvest',
                'permissions' => '["wifi_harvests_list"]',
                'parent_id' => 40,
                'lft' => 15,
                'rgt' => 16,
                'depth' => 2,
                'created_at' => '2024-08-15 22:35:54',
                'updated_at' => '2024-08-15 22:35:54',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'label' => 'Expenses',
                'icon' => 'las la-shapes',
                'url' => 'expense',
                'permissions' => '["expenses_list"]',
                'parent_id' => 41,
                'lft' => 19,
                'rgt' => 20,
                'depth' => 2,
                'created_at' => '2024-08-24 08:28:50',
                'updated_at' => '2024-08-24 08:37:46',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'label' => 'Categories',
                'icon' => 'las la-file-alt',
                'url' => 'category',
                'permissions' => '["categories_list"]',
                'parent_id' => NULL,
                'lft' => 46,
                'rgt' => 47,
                'depth' => 1,
                'created_at' => '2024-08-24 08:40:31',
                'updated_at' => '2024-08-26 11:47:56',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'label' => 'Hotspot Vouchers',
                'icon' => 'las la-rss-square',
                'url' => 'hotspot-voucher',
                'permissions' => '["hotspot_vouchers_list"]',
                'parent_id' => 40,
                'lft' => 13,
                'rgt' => 14,
                'depth' => 2,
                'created_at' => '2024-08-26 12:36:09',
                'updated_at' => '2024-08-26 12:36:09',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'label' => 'Reports',
                'icon' => 'las la-chalkboard-teacher',
                'url' => 'report',
                'permissions' => '["reports_list"]',
                'parent_id' => NULL,
                'lft' => 30,
                'rgt' => 31,
                'depth' => 1,
                'created_at' => '2024-08-28 07:42:24',
                'updated_at' => '2024-08-28 07:42:24',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'label' => 'Cash Inflows',
                'icon' => 'las la-coins',
                'url' => NULL,
                'permissions' => NULL,
                'parent_id' => NULL,
                'lft' => 10,
                'rgt' => 17,
                'depth' => 1,
                'created_at' => '2024-08-28 19:30:27',
                'updated_at' => '2024-08-28 19:31:18',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'label' => 'Cash Outflows',
                'icon' => 'las la-donate',
                'url' => NULL,
                'permissions' => NULL,
                'parent_id' => NULL,
                'lft' => 18,
                'rgt' => 21,
                'depth' => 1,
                'created_at' => '2024-08-28 19:32:04',
                'updated_at' => '2024-08-28 19:32:04',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}