<?php


return [

    /*
    |--------------------------------------------------------------------------
    | NavLink Billing System Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines are used in NavLink Billing System
    | messages that we need to display to the user. You are free to modify
    | these language lines according to your application's requirements.
    |
    */
    // Misc.
    
    // Accounts
    
    'account' => 'Account',
    'account_field_validation' => 'The account field is required.',
    'account_name' => 'Acount Name (Customer)',
    'account_names' => 'Acount Names (Customers)',
    'account_google_map_coordinates' => 'Coordiantes',
    
    // Account Status
    'account_status' => 'Account Status',
    'account_statuses' => 'Account Statuses',
    
    // Billing 
    'billing_date_start' => 'Date Start',
    'billing_date_end' => 'Date End',
    'billing_date_cut_off' => 'Date Cut Off',
    'billing_particulars' => 'Particulars',
    'billing_description' => 'Description',

    // Billing Type
    'billing_type' => 'Billing Type',
    'billing_type_id_hint' => '<span class="text-success">The Installation Fee does not require particulars; it will automatically populate based on the account records or be generated by the system.</span>',

    // Contract Period
    'contract_period' => 'Contract Period',
    'contract_periods' => 'Contract Periods',
    
    // Customers
    'customer' => 'Customer',
    'customer_signature' => 'Please sign here',
    'customer_select_field' => 'The customer field is required.',

    // Customer Credits
    'remaining_credits' => 'Remaining Credits',
    'latest_updated' => 'Last Updated',
    
    // OTC 
    'otc' => 'One-Time Charge',
    'otcs' => 'One-Time Charges',
    
    // Planned Application
    'planned_application' => 'Planned Applicaton',
    'planned_applications' => 'Planned Applicatons',
    
    // Planned Application Type
    'planned_application_type' => 'Planned Applicaton Type',
    'planned_applications_types' => 'Planned Applicaton Types',
    

    // Subscription
    'subscription' => 'Subscription',
    'subscriptions' => 'Subscriptions',
    
    

];
